num_receivers: 3
map:
  - layer: "C:\\Code\\Console\\kosobudno.tif"
  #- layer: "resources/ortofot_topocentryczny.bmp"
targets:
  - id: "Target1"
    parameters:
      IP:
        value: 153.19.108.122
        readable: true 
      Port:
        value: 7000
        readable: true   
receivers:
  - id: RPI1
    param_monitor:
      Serial:
        value: xxx
        readable: true
      IP:
        value: xxx
        readable: true 
      MASK:
        value: xxx
        readable: true
      Mode:
        value: xxx
        readable: true
      BatPerc:
        value: xxx
        readable: true
      StPPS:
        value: xxx
        readable: true
      RPiProc:
        value: xxx
        readable: true
      ACT_SRate:
        value: xxx
        readable: true
      ACT_Nagrywanie:
        value: xxx
        readable: true
      ACT_AktHydro:
        value: xxx
        readable: true
      ACT_AktGPS:
        value: xxx
        readable: true
      ACT_AktStreaming:
        value: xxx
        readable: true
      ACT_RecDur:
        value: xxx
        readable: true
      ACT_Pause:
        value: xxx
        readable: true
    param_control:
      SRate:
        value: xxx
        readable: true
      Nagrywanie:
        value: xxx
        readable: false
      AktHydro:
        value: xxx
        readable: false
      AktGPS:
        value: xxx
        readable: false
      AktStreaming:
        value: xxx
        readable: false
      RecDur:
        value: xxx
        readable: true
      Pause:
        value: xxx
        readable: true
    sftp: 
      host: '192.168.0.102' #host: '172.23.21.12'
      user: 'pi'
      password: 'raspberry'
      port: 22      
      keepalive_s: 30
      remote_dirs:
        streaming: "/home/pi/bsp/streaming"
        gps: "/home/pi/bsp/GPS"
        config: "/home/pi/bsp/PARAM"
        monitor_file: "PARAM_RPI1_MONITOR.txt"
        control_file: "PARAM_RPI1_CONTROL.txt"
        max_retries: 3
      local_dirs:                          
        streaming: "C:\\Pi_loc\\RPI1\\streaming"
        gps: "C:\\Pi_loc\\RPI1\\GPS"
        config: "C:\\Pi_loc\\RPI1\\PARAM"
  - id: RPI2
    param_monitor:
      Serial:
        value: xxx
        readable: true
      IP:
        value: xxx
        readable: true 
      MASK:
        value: xxx
        readable: true
      Mode:
        value: xxx
        readable: true
      BatPerc:
        value: xxx
        readable: true
      StPPS:
        value: xxx
        readable: true
      RPiProc:
        value: xxx
        readable: true
      ACT_SRate:
        value: xxx
        readable: true
      ACT_Nagrywanie:
        value: xxx
        readable: true
      ACT_AktHydro:
        value: xxx
        readable: true
      ACT_AktGPS:
        value: xxx
        readable: true
      ACT_AktStreaming:
        value: xxx
        readable: true
      ACT_RecDur:
        value: xxx
        readable: true
      ACT_Pause:
        value: xxx
        readable: true
    param_control:
      SRate:
        value: xxx
        readable: true
      Nagrywanie:
        value: xxx
        readable: false
      AktHydro:
        value: xxx
        readable: false
      AktGPS:
        value: xxx
        readable: false
      AktStreaming:
        value: xxx
        readable: false
      RecDur:
        value: xxx
        readable: true
      Pause:
        value: xxx
        readable: true
    sftp: 
      host: '192.168.0.220' #host: '172.23.21.12'
      user: 'pi'
      password: 'raspberry'
      port: 22      
      keepalive_s: 30
      remote_dirs:
        streaming: "/home/pi/bsp/streaming"
        gps: "/home/pi/bsp/GPS"
        config: "/home/pi/bsp/PARAM"
        monitor_file: "PARAM_RPI2_MONITOR.txt"
        control_file: "PARAM_RPI2_CONTROL.txt"
        max_retries: 3
      local_dirs:                          
        streaming: "C:\\Pi_loc\\RPI2\\streaming"
        gps: "C:\\Pi_loc\\RPI2\\GPS"
        config: "C:\\Pi_loc\\RPI2\\PARAM"
  - id: RPI3
    param_monitor:
      Serial:
        value: xxx
        readable: true
      IP:
        value: xxx
        readable: true 
      MASK:
        value: xxx
        readable: true
      Mode:
        value: xxx
        readable: true
      BatPerc:
        value: xxx
        readable: true
      StPPS:
        value: xxx
        readable: true
      RPiProc:
        value: xxx
        readable: true
      ACT_SRate:
        value: xxx
        readable: true
      ACT_Nagrywanie:
        value: xxx
        readable: true
      ACT_AktHydro:
        value: xxx
        readable: true
      ACT_AktGPS:
        value: xxx
        readable: true
      ACT_AktStreaming:
        value: xxx
        readable: true
      ACT_RecDur:
        value: xxx
        readable: true
      ACT_Pause:
        value: xxx
        readable: true
    param_control:
      SRate:
        value: xxx
        readable: true
      Nagrywanie:
        value: xxx
        readable: false
      AktHydro:
        value: xxx
        readable: false
      AktGPS:
        value: xxx
        readable: false
      AktStreaming:
        value: xxx
        readable: false
      RecDur:
        value: xxx
        readable: true
      Pause:
        value: xxx
        readable: true
    sftp: 
      host: '192.168.0.230' #host: '172.23.21.12'
      user: 'pi'
      password: 'raspberry'
      port: 22      
      keepalive_s: 30
      remote_dirs:
        streaming: "/home/pi/bsp/streaming"
        gps: "/home/pi/bsp/GPS"
        config: "/home/pi/bsp/PARAM"
        monitor_file: "PARAM_RPI3_MONITOR.txt"
        control_file: "PARAM_RPI3_CONTROL.txt"
        max_retries: 3
      local_dirs:                          
        streaming: "C:\\Pi_loc\\RPI3\\streaming"
        gps: "C:\\Pi_loc\\RPI3\\GPS"
        config: "C:\\Pi_loc\\RPI3\\PARAM"
logging:
  file: "logs/log.log"
  file_level: "DEBUG"
  gui_level: "INFO"
  ring_capacity: 2000
  rotate: true
  max_bytes: 5000000
  backup_count: 5